/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

export * from '../../t3flip/client/js/generated/accounts';
export * from '../../t3flip/client/js/generated/errors';
export * from '../../t3flip/client/js/generated/instructions';
export * from '../../t3flip/client/js/generated/programs';
