name: Request Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

permissions:
  issues: write
  pull-requests: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment tagging reviewers
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            👋 Hey reviewers! Please have a look at this PR.

            @GauravBurande @loganyu @code-sleuth @AndreiaCanadas @Zanda256 @ningthoujamSwamikumar @kirtiraj22 @senzenn
            
